language: node_js
node_js:
  - "8.11.3"
before_install:
  - sudo apt-get install liblapack-dev liblapacke-dev
env:
  - CXX=g++-6.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6.1
